#!/usr/bin/tclsh

# Messages UNO
::msgcat::mcset fr uno_welcome "Bienvenue ! Tapez \002!uno\002 pour lancer une partie de %s\017 :) (Liste de mes commandes : \002!unocmds\002)"
::msgcat::mcset fr uno_unocmd "\00304UNO :\017 !uno par \00302%s\017 sur \00302%s\017."
::msgcat::mcset fr uno_startalready0 "%s\00306 Désolé, une partie est en cours sur un autre salon."
::msgcat::mcset fr uno_startalready1 "%s\00306 Une partie est déjà en cours !"
::msgcat::mcset fr uno_started "\00304UNO :\017 Partie démarrée sur \00302%s."
::msgcat::mcset fr uno_pubjoin "%s\003 \00300,12Tapez jo pour rejoindre la partie ! Vous avez %d secondes."
::msgcat::mcset fr uno_noplayers "%s \00300,03Aucun joueur, prochain jeu dans %d secondes."
::msgcat::mcset fr uno_stopnoplayers "%s \00300,06Partie stoppée, %d tours non joués. Tapez !uno pour recommencer une partie."
::msgcat::mcset fr uno_join0 "%s\017 rejoint la partie %s"
::msgcat::mcset fr uno_join1 "\00304UNO : \00302%s\017 rejoint la partie."
::msgcat::mcset fr uno_welcome0 "\00300,06 Bienvenue dans le jeu de \017%s"
::msgcat::mcset fr uno_welcome1 "\00300,10 \002%d\002 joueurs dans cette partie\00300,06 %s \003"
::msgcat::mcset fr uno_start "%s\017 commence. La première carte est %s"
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
::msgcat::mcset fr uno_
